on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: ${{ matrix.racket-version }}
      - name: Installing punct-tests and its dependencies
        run: raco pkg install --no-docs --auto --name punct-tests
      - name: Compiling punct-tests and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps punct-tests
      - name: Testing punct-tests
        run: raco test -x -p punct-tests
